name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Update submodules
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: make bonus
      run: make bonus
    - name: Test with 3 elements
      run:  make test ELEMENTS=3 TESTS=100
    - name: Test with 5 elements
      run:  make test ELEMENTS=5 TESTS=100
    - name: Test with 100 elements
      run:  make test ELEMENTS=100 TESTS=100
    - name: Test with 500 elements
      run:  make test ELEMENTS=500 TESTS=100

  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: alexandregv/norminette-action@v3
